import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-secondary-container": "#b8bfa3",
        "charcoal-field": "#1A1A1B",
        "background": "#131313",
        "tactical-black": "#0D0D0D",
        "error": "#ffb4ab",
        "surface": "#131313",
        "on-tertiary-fixed-variant": "#464747",
        "on-surface-variant": "#e3bfb4",
        "primary-fixed-dim": "#ffb59e",
        "on-error": "#690005",
        "on-tertiary-fixed": "#1b1c1c",
        "stark-white": "#FFFFFF",
        "secondary-fixed-dim": "#c3c9ae",
        "surface-container-low": "#1c1b1b",
        "secondary-container": "#484e38",
        "on-secondary-fixed": "#181e0c",
        "on-error-container": "#ffdad6",
        "secondary-fixed": "#dfe6c9",
        "on-secondary-fixed-variant": "#434934",
        "secondary": "#c3c9ae",
        "on-tertiary-container": "#292a2a",
        "surface-container-lowest": "#0e0e0e",
        "inverse-primary": "#ad3300",
        "on-primary-container": "#521400",
        "tertiary-fixed-dim": "#c7c6c6",
        "on-primary-fixed": "#390b00",
        "primary-container": "#f85e27",
        "surface-container-highest": "#353534",
        "primary": "#ffb59e",
        "surface-bright": "#3a3939",
        "surface-tint": "#ffb59e",
        "tertiary": "#c7c6c6",
        "outline-variant": "#5a4139",
        "signal-orange": "#FF5F1F",
        "surface-container": "#201f1f",
        "error-container": "#93000a",
        "primary-fixed": "#ffdbd0",
        "on-secondary": "#2d331f",
        "on-background": "#e5e2e1",
        "on-tertiary": "#303031",
        "on-surface": "#e5e2e1",
        "tertiary-fixed": "#e3e2e2",
        "surface-variant": "#353534",
        "surface-container-high": "#2a2a2a",
        "surface-dim": "#131313",
        "outline": "#aa8a80",
        "tertiary-container": "#919190",
        "on-primary-fixed-variant": "#842500",
        "operator-green": "#2E3325",
        "inverse-on-surface": "#313030",
        "on-primary": "#5d1800",
        "inverse-surface": "#e5e2e1",
      },
      borderRadius: {
        "DEFAULT": "0px",
        "lg": "0px",
        "xl": "0px",
        "full": "9999px"
      },
      spacing: {
        "section-gap": "80px",
        "stack-lg": "32px",
        "margin-edge": "32px",
        "stack-md": "16px",
        "unit": "8px",
        "stack-sm": "8px",
        "gutter": "24px"
      },
      fontFamily: {
        "headline-lg-mobile": ["Archivo Narrow", "sans-serif"],
        "data-mono": ["JetBrains Mono", "monospace"],
        "label-caps": ["JetBrains Mono", "monospace"],
        "headline-md": ["Archivo Narrow", "sans-serif"],
        "display-xl": ["Archivo Narrow", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-lg": ["Archivo Narrow", "sans-serif"],
        "body-md": ["Inter", "sans-serif"]
      },
      fontSize: {
        "headline-lg-mobile": ["32px", { lineHeight: "1.2", fontWeight: "700" }],
        "data-mono": ["12px", { lineHeight: "1.4", fontWeight: "500" }],
        "label-caps": ["14px", { lineHeight: "1.0", letterSpacing: "0.1em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "600" }],
        "display-xl": ["72px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "800" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-lg": ["48px", { lineHeight: "1.2", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }]
      }
    },
  },
  plugins: [],
};
export default config;
